# Generated by Django 3.0.6 on 2020-09-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=150)),
            ],
        ),
    ]
